server:
  port: 9999
spring:
  application:
    name: spring-api-gateway

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
    bus:
      refresh:
        enabled: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    connection-timeout: 5

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_URL:localhost:8443}/realms/event-management/protocol/openid-connect/certs
          issuer-uri: http://${KEYCLOAK_URL:localhost:8443}/realms/event-management


    # Rotas para serviços externos 

    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8091 # Endereço do User Service
          predicates:
            - Path=/api/users/** # Requisições que começam com /api/users/

loki:
  url: "http://${LOKI_URL:localhost}:3100/loki/api/v1/push"
  jobName: ${LOKI_JOB_NAME:spring-api-gateway}

management:
  endpoint:
    health:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true


logging:
  level:
    root: INFO
    br.dev.leandro.spring.cloud.filter.AuditGlobalFilter: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO
    io.github.resilience4j.circuitbreaker: INFO
    org.springframework.cloud: INFO
    org.springframework.cloud.config: INFO
    com.github.loki4j.logback: INFO
    org.springframework.security: INFO
    org.springframework.cloud.bus: INFO