spring: 
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://spring-user:8081

          predicates:
            - Path=/users/**  
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user
management:
  endpoints:
    web:
      exposure:
        include: '*'

