spring: 
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://spring-user:8091
          predicates:
            - Path=/api/users/** # Requisições que começam com /api/users/
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user
management:
  endpoints:
    web:
      exposure:
        include: '*'

