management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'



otel:
  metrics:
    exporter: none
  traces:
    exporter: otlp
    sampler:
      always_on
  exporter:
    otlp:
      endpoint: http://tempo:3200
      logs:
        protocol: http/protobuf

logging:
  level:
    io.opentelemetry: DEBUG

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}  # RabbitMQ rodando no Docker
