spring:
  config:
    server:
      native:
        default-label: main
        add-label-locations: false
        search-locations:
          - file://${HOME}/Dev/workspace/Leandro-Labs/spring_config_repo/{application}
loki:
  url: "http://${LOKI_URL:localhost}:3100/loki/api/v1/push"
  jobName: ${LOKI_JOB_NAME:spring-user}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    refresh:
      enabled: true


app:
  mensagem:
    usuario: "Olá Usuário, bom dia atualizado!"     

logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot: INFO
    com.github.loki4j: INFO
    org.springframework.security: DEBUG
    org.springframework.cloud.bus: INFO