server:
  port: 8091
spring:
  application:
    name: spring-user
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
    bus:
      refresh:
        enabled: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    connection-timeout: 5

loki:
  url: "http://${LOKI_URL:localhost}:3100/loki/api/v1/push"
  jobName: ${LOKI_JOB_NAME:spring-user}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    refresh:
      enabled: true


app:
  mensagem:
    usuario: "Olá Usuário, bom dia atualizado!"     

logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot: INFO
    com.github.loki4j: INFO
    org.springframework.security: DEBUG
    org.springframework.cloud.bus: INFO